FROM python:3.10
WORKDIR /app
COPY requirements.txt requirements.txt
RUN apt update && apt install build-essential
RUN pip install -U setuptools
RUN pip install -r requirements.txt
COPY . .
CMD ["python", "api.py"]
