name: development
services:
    galaxygpt-api:
        pull_policy: build
        env_file: .env.development
        depends_on:
            - qdrant
        ports: !override
            - "6363:3636"

    qdrant:
        ports:
            - "6223:6333"
            - "6224:6334"