FROM python:3.10

WORKDIR /app

COPY requirements.txt requirements.txt

RUN apt update && apt install build-essential -y

RUN pip install --no-cache-dir -U -r requirements.txt

COPY . .

CMD ["python", "api.py"]
