services:
  galaxygpt-api:
    image: galaxygpt-api
    restart: unless-stopped
    depends_on:
        - qdrant
    ports:
      - "3636:3636"
    build:
      context: .
      dockerfile: galaxygpt-api/Dockerfile

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    restart: unless-stopped
# Uncomment the following lines if you plan on using the Qdrant API directly
#    ports:
#      - "6333:6333"
#      - "6334:6334"
    expose:
      - "6333"
      - "6334"
      - "6335"
    volumes:
        - qdrant-data:/qdrant/storage

volumes:
    qdrant-data: