name: production
services:
  galaxygpt-api:
    env_file: .env.production
    environment:
        - ASPNETCORE_ENVIRONMENT=Production
    labels:
        - "com.centurylinklabs.watchtower.enable=true"
  qdrant:
    ports:
        - "6333:6333"
        - "6334:6334"